spring:
  mail:
    host: smtp.qq.com
    username:  840326461@qq.com
    password:  kcyjntjloiorbbib
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          timeout: 0
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode:   HTML
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html; charset=utf-8

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

  datasource:
    url: jdbc:mysql://localhost:3306/mycourses?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8088
  max-http-header-size: 1048576
